# This file contains aliases which allow for 'global' installed
# npm packages to be run inside the Thumb powershell. The code here is
# generated by the 'Thumpm-Install-g' function in thumbProfile.ps1

Write-Host "NPM Aliases Initializing - httpster3"

#Set-Thumb-Alias httpster "node pf\node_modules\httpster\bin\httpster"
function httpster3(){
    # node thumbLoc("pf\node_modules\httpster\bin\httpster")
    Start-Process -FilePath (thumbLoc('pf\nodejs\node.exe')) -ArgumentList httpster, args
}

# this is the right track...
function httpster3(){
    # node thumbLoc("pf\node_modules\httpster\bin\httpster")
    Start-Process -FilePath (thumbLoc('pf\nodejs\node.exe')) -ArgumentList (thumbLoc('pf\node_modules\httpster\bin\httpster')), args -NoNewWindow -Wait
}