# This file contains aliases which allow for 'global' installed
# npm packages to be run inside the Thumb powershell. The code here is
# generated by the 'Thumpm-Install-g' function in thumbProfile.ps1
